.TH SCATOOL.CONF 5 "2021 May 25" "sca-server-report" "Supportconfig Analysis Manual"
.SH NAME
scatool.conf - Supportconfig Analysis Tool Configuration File
.SH DESCRIPTION
The \fBscatool.conf\fR file has default values for \fBscatool\fR.
.SH GLOBAL VARIABLES
.TP
REMOVE_ARCHIVE
Once the \fBscatool\fR processes the supportconfig archive, delete the archive, its .md5 file and extracted directory leaving only the html report file. REMOVE_ARCHIVE is disabled by default leaving the original archive in place.
.RS
Valid options: 0 = Disable remove archive mode, 1 = Enable remove archive mode
.RE
.RS
Default: 0
.RE
.TP
OUTPUT_PATH
The directory where the HTML report file is saved.
.RS
Default: (Empty)
.RE
.TP
OUTPUT_EMAIL_LIST
The email address(es) where HTML reports should be sent. A comma or space separated list of email addresses.
.RS
Default: (Empty)
.RE
.TP
REMOTE_SC_PATH
The remote supportconfig path where the supportconfig tar ball is temporarily saved while running on the remote server. You generally don't want to change this path.
.RS
Default: /var/log
.RE
.TP
SCA_LIBRARY_PATH
The base SCA Tool library path. Pattern libraries are located here. 
.RS
Default: /usr/lib/sca/
.RE
.TP
SCA_PATTERN_PATH
The base pattern directory for all patterns.
.RS
Default: /usr/lib/sca/patterns/
.RE
.TP
BASHLIB
The Bash library location for the supportconfig pattern repository. The bash patterns \fBscatool\fR uses requires bash libraries located in this directory.
.RS
Default: /usr/lib/sca/patterns/lib/bash
.RE
.TP
PERL5LIB
The Perl library location for the supportconfig pattern repository. The perl patterns \fBscatool\fR uses requires perl libraries located in this directory.
.RS
Default: /usr/lib/sca/patterns/lib/perl
.RE
.TP
PYTHONPATH
The Python library location for the supportconfig pattern repository. The python patterns \fBscatool\fR uses requires python libraries located in this directory.
.RS
Default: /usr/lib/sca/patterns/lib/python
.RE
.TP
LOGLEVEL
The SCA Tool log level.
.RS
Valid options: LOGLEVEL_NORMAL and LOGLEVEL_VERBOSE
.RE
.RS
Default: LOGLEVEL_NORMAL
.RE
.SH AUTHOR
Jason Record <jason.record@suse.com>
.SH COPYRIGHT
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; version 2 of the License.
.PP
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
.PP
You should have received a copy of the GNU General Public License
along with this program; if not, see <http://www.gnu.org/licenses/>.
.SH SEE ALSO
.BR \fBscatool\fR (8)

